### ISSUE TITLE
nan in training gardenvase case

### ISSUE THREAD

**Issue by flyingGH** [video2game/video2game#7]
Hello, thank you for your great work.
I meet nan problem in gradenvase case trainning case.
I make follwing modications for decrease memory consumption:
1/4 sampling for training data.

it that cause the nan?
or other aspect? thank you~

**Comment by anonymous5433** [comment]
> Hello, thank you for your great work. I meet nan problem in gradenvase case trainning case. I make follwing modications for decrease memory consumption: 1/4 sampling for training data.
> 
> it that cause the nan? or other aspect? thank you~

Hello,I've met nan problem you've met before.
I want to know if you have solve the problem?
Wish you have a good day!

**Comment by xiahongchi** [comment]
Sorry for late reply. Could you show me your modifications on config?

**Comment by anonymous5433** [comment]
> Sorry for late reply. Could you show me your modifications on config?

I've solve this problem,thanks for your reply!But when I used the kitti_baking_pretrain_export.sh file to export the UV decomposition result files, I encountered the following error:Traceback (most recent call last):
  File "baking_pretrain_export.py", line 436, in <module>
    ipdb.set_trace()
  File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "baking_pretrain_export.py", line 169, in _export_obj
    atlas = xatlas.Atlas()
  File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/neighbors/_unsupervised.py", line 166, in fit
    return self._fit(X)
  File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 435, in _fit
    X = self._validate_data(X, accept_sparse="csr")
  File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/utils/validation.py", line 808, in check_array
    % (n_samples, array.shape, ensure_min_samples, context)
ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required.After debugging, I found that during the second call to the _export_obj function, all values in vt_np became NaN.May I ask you how to solve this problem？

**Comment by anonymous5433** [comment]
> > Sorry for late reply. Could you show me your modifications on config?
> 
> I've solve this problem,thanks for your reply!But when I used the kitti_baking_pretrain_export.sh file to export the UV decomposition result files, I encountered the following error:Traceback (most recent call last): File "baking_pretrain_export.py", line 436, in ipdb.set_trace() File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "baking_pretrain_export.py", line 169, in _export_obj atlas = xatlas.Atlas() File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/neighbors/_unsupervised.py", line 166, in fit return self._fit(X) File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 435, in _fit X = self._validate_data(X, accept_sparse="csr") File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data X = check_array(X, **check_params) File "/home/ubuntu/miniconda3/envs/video2game/lib/python3.7/site-packages/sklearn/utils/validation.py", line 808, in check_array % (n_samples, array.shape, ensure_min_samples, context) ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required.After debugging, I found that during the second call to the _export_obj function, all values in vt_np became NaN.May I ask you how to solve this problem？

I use the config you update on github and I didn't change,but only cancled using segmantic information.

**Comment by xiahongchi** [comment]
it's an issue on your xatlas calling. maybe printing the input to xatlas could be helpful for debugging

**Comment by anonymous5433** [comment]
> it's an issue on your xatlas calling. maybe printing the input to xatlas could be helpful for debugging
Thanks for your reply!I've found that my num is too low.Sorry to bother you a lot,but I want to ask one more question:In baking_pretrain.py you used center pos_trans.pkl,but I didn't fount where to generate it in your code.Is that a .pkl I need to generate myself?

**Comment by anonymous5433** [comment]
> it's an issue on your xatlas calling. maybe printing the input to xatlas could be helpful for debugging

In baking_pretrain.py you used center pos_trans.pkl,but I didn't fount where to generate it in your code.Is that a .pkl I need to generate myself?
